#!/usr/bin/env python2
import numpy as np, argparse, sys
from scipy import ndimage
from enlib import enmap
np.seterr(all="ignore")
parser = argparse.ArgumentParser()
parser.add_argument("imap")
parser.add_argument("hitmap", nargs="?", default=None)
parser.add_argument("omap")
parser.add_argument("-F", "--filter", action="append", help="Filter specification. Can be specified multiple times. Formats: g:lcut = gaussian filter, lowpass for positive lcut, highpass for negative. b:lcut:alpha = butterworth filter. Lowpass for positive alpha, highpass for negative.")
parser.add_argument("-m", "--mode", type=str, default="a")
parser.add_argument("-s", "--slice", type=str, default=None)
parser.add_argument("-L", "--limit", type=float, default=0.10)
parser.add_argument("-e", "--extent-model", type=str, default=None)
parser.add_argument("-v", action="count")
args = parser.parse_args()

filter_specs = args.filter or ["b:200:-5"]

if args.extent_model is not None:
	enmap.extent_model.append(args.extent_model)

m = enmap.read_map(args.imap)
if args.slice:
	m = eval("m"+args.slice)
ishape = m.shape
m = m.preflat
if args.hitmap != None:
	w = enmap.read_map(args.hitmap)
	while w.ndim > 2: w = w[0]
else:
	w = enmap.zeros(m.shape[-2:], m.wcs, dtype=m.dtype)+1

samps = w.reshape(-1)[::100]
samps = samps[samps!=0]
typ   = np.median(samps)
mask  = np.any(np.isnan(m),0)|np.isnan(w)|(w<typ*1e-3)
m[:,mask] = 0
w[mask] = 0
# The function of the mask is to apodize edges, so smooth out the middle
w0 = typ*0.10
w = (1/(1+w0/w)).astype(m.dtype)
wm = m*w
del samps

print np.std(m), np.std(w), np.std(wm)

# Pad to fft-friendly size
def filter_gauss(l, lsigma):
	f = np.exp(-0.5*(l/lsigma)**2)
	return f if lsigma > 0 else 1-f
def filter_butter(l, lknee, alpha):
	return 1.0/(1+(l/lknee)**alpha)

# Set up filter
for mode in args.mode:
	l = wm.lmap()
	if args.v > 0: print mode
	if   mode == "v": l = np.abs(l[1])
	elif mode == "h": l = np.abs(l[0])
	elif mode == "a": l = np.sum(l**2,0)**0.5
	else: raise ValueError("Unrecognized mode " + mode)

	filters = enmap.zeros(wm.shape, wm.wcs, dtype=wm.dtype)
	for i, fspec in enumerate(filter_specs):
		filter = l*0+1
		for fstr in fspec.split(","):
			toks = fstr.split(":")
			if toks[0] in ["g","gauss"]:
				lsigma = float(toks[1])
				filter *= filter_gauss(l, lsigma)
			elif toks[0] in ["b", "butter", "butterworth"]:
				lknee = float(toks[1])
				alpha = float(toks[2])
				print "a"
				filter *= filter_butter(l, lknee, alpha)
				print "b"
			else: raise ValueError("Unknown filter type: " + toks[0])
		filters[i] = filter
		del filter
	del l
	print "moo"
	for j in range(i+1,len(filters)):
		filters[j] = filters[i]
	# Apply filter
	print np.std(filters)
	wm  = enmap.map2harm(wm)
	wm *= filters
	del filters
	wm  = enmap.harm2map(wm)

# And recover filtered map
m   = wm/w
del wm, w
m[:,mask] = np.nan
m   = np.reshape(m, ishape)

enmap.write_map(args.omap, m)
