#!/usr/bin/env bash
awk '{
	for(i=1;i<=NF;i++){
		a[ARGIND,i]+=$i
		aa[ARGIND,i]+=$i**2
		n[ARGIND,i]++
		am=ARGIND
	}
}END{
	for(i=1;i<=am;i++){
		for(j=1;j<=11;j++){
			N=n[i,j]<1?1:n[i,j]
			v=a[i,j]/N
			vv=aa[i,j]/N
			s=(vv-v**2)**0.5
			printf(" %9.4f %9.4f",v,s)
		}
		printf("\n")
	}
}' "$@"
